services:
  app:
    build:
      context: .
      dockerfile: lala.dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      - PORT=3000
    command: npm run dev
